#数据库连接信心
spring:
  application:
    name:spring-boot-tlias-management

  #数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/tlias?useUnicode=true&character
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名
    map-underscore-to-camel-case: true